#!/usr/bin/env bash
#script that uses if, elif statement
y=1
while [ $y -le 10 ]
do
	if [ $y -eq 4 ]
	then
		echo "bad luck"
	elif [ $y -eq 8 ]
	then 
		echo "good luck"
	else
		echo "Best School"
	fi
	((y++))
done
