#!/usr/bin/env bash
#script that uses case statement
y=1
while [ $y -le 20 ]
do
	echo "$y"
	case $y in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((y++))
done
